Repository openrca/orca, pull requests merged in 2020-04, with the labels that each got.

#46 Parametrize Helm chart
  helm/orca/charts/arangodb/templates/deployment.yaml
  helm/orca/charts/arangodb/templates/service.yaml
  helm/orca/charts/neo4j/templates/deployment.yaml
  helm/orca/charts/neo4j/templates/service.yaml
  helm/orca/config/orca.yaml
  helm/orca/requirements.yaml
  helm/orca/templates/configmap.yaml
  helm/orca/values.yaml
Labels: enhancement

#43 Remove Neo4j graph backend
  docker-compose.yaml
  helm/orca/charts/neo4j/Chart.yaml
  helm/orca/charts/neo4j/templates/_helpers.tpl
  helm/orca/charts/neo4j/templates/deployment.yaml
  helm/orca/charts/neo4j/templates/secret.yaml
  helm/orca/charts/neo4j/templates/service.yaml
  helm/orca/charts/neo4j/values.yaml
  helm/orca/requirements.yaml
  helm/orca/templates/configmap.yaml
  helm/orca/values.yaml
  orca/common/config.py
  orca/graph/drivers/__init__.py
  orca/graph/drivers/neo4j.py
  requirements.txt
Labels: enhancement

#33 Add contribution guide
  CONTRIBUTING.md
Labels: documentation

#56 Fix non-deterministic link source-target ordering
  orca/topology/linker.py
Labels: bug

#57 Filter out soft-deleted elements in graph operations
  orca/graph/drivers/arangodb.py
Labels: bug

#53 Complete mapping of Prometheus alerts
  helm/orca/config/alerts-mapping.yaml
Labels: enhancement
